spring:
  application:
    name: "nozama-orderinfoupdater"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/nozama_orderinfo_db?useSSL=false"
    username: nozama_dba
    password: nozama19

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update

  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/

  jackson:
    serialization:
      fail-on-empty-beans: false

  batch:    jdbc:      initialize-schema: "always"
server:
  port: 8087
#https://howtodoinjava.com/spring-boot2/logging/configure-logging-application-yml/
logging:
  file:
    path: "../logs"
    name: "${logging.file.path}/${spring.application.name}_log.log"
  level:
    org:
      hibernate:
        SQL: ERROR
        type: TRACE

  config: "classpath:orderinfoupdater-logging-config.xml"

kafka:
  server:
    path: "localhost:9092"
  topic: "order.info.updater"

nozama:
  api:
    gateway:
      serviceid: "nozama-api-gateway"