#https://stackoverflow.com/questions/41401009/load-balancer-does-not-have-available-server-for-client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
    prefer-ip-address: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

jwt:
  secret: nozama
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: INFO
      springframework:
        security: DEBUG
        type: ERROR

server:
  error:
    include-stacktrace: never
  port: 8089
spring:
  main:
    allow-circular-references: true
  application:
    name: nozama-userauthservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: nozama19
    url: jdbc:mysql://localhost:3310/nozama_user_db?allowPublicKeyRetrieval=true&useSSL=false
    username: nozama_dba
  jackson:
    serialization:
      fail-on-empty-beans: false
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

## This is the way we can provide the service proxy url and port to reach the other msa
## The URL is pointing to API Gateway and its port number
userservice :
  ribbon :
    listOfServers : http://${nozama_api_host:localhost}:${nozama_api_port:8081}

feign:
  circuitbreaker:
    enabled: true
    
#Prometheus
management:
  server:
    port: 8762