eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
    prefer-ip-address: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: INFO

server:
  port: 8089
  error:
    include-stacktrace: never

spring:
  application:
    name: nozama-userauthservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: nozama19
    url: jdbc:mysql://nozama-mysql-container:3306/nozama_user_auth_db?allowPublicKeyRetrieval=true&useSSL=false
    username: nozama_dba
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  secret: nozama

## This is the way we can provide the service proxy url and port to reach the other msa
## The URL is pointing to API Gateway and its port number
userservice :
  ribbon :
    listOfServers : http://${nozama_api_host:localhost}:${nozama_api_port:8081}

feign:
  circuitbreaker:
    enabled: true