eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  port: 8089
  error:
    include-stacktrace: never
spring:
  application:
    name: nozama-userauthservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: nozama19
    url: jdbc:mysql://nozama-mysql-container:3306/nozama_user_auth_db?allowPublicKeyRetrieval=true&useSSL=false
    username: nozama_dba
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  secret: nozama