## NOZAMA_SERVICE_PROFILE value from the OS Environment variable value, if no set it takes default value "dev"
spring:
    profiles:
      active: ${NOZAMA_SERVICE_PROFILE:local}

springdoc:
  api-docs:
    path: /cart/v3/api-docs
  swagger-ui:
    path: /cart/swagger-ui.html