server:
  port: 8090 
  ssl:
    key-store: /cert/nozama.jks
    key-store-password: nozama19
    key-alias: nozama
    key-store-type: JKS

eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 120000
##This property has to be true, so that it uses the IP address, instead of localhost or 127.0.0.1
    prefer-ip-address: true

spring:
  application:
    name: nozama-api-gateway
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
      - id: nozama-productservice
        uri: https://nozama-product-service:8082
        predicates:
        - Path=/category/**
      - id: nozama-productservice
        uri: https://nozama-product-service:8082
        predicates:
        - Path=/product/**
      - id: nozama-productservice
        uri: https://nozama-product-service:8082
        predicates:
        - Path=/product-api/**
      - id: nozama-productservice
        uri: https://nozama-product-service:8082
        predicates:
        - Path=/product-sw/**
      - id: nozama-orderservice
        uri: https://nozama-order-service:8094
        predicates:
        - Path=/order/**
      - id: nozama-orderservice
        uri: https://nozama-order-service:8094
        predicates:
        - Path=/order-sw/**
      - id: nozama-orderservice
        uri: https://nozama-order-service:8094
        predicates:
        - Path=/order-api/**
      - id: nozama-userservice
        uri: https://nozama-user-service:8081
        predicates:
        - Path=/user/**
      - id: nozama-userservice
        uri: https://nozama-user-service:8081
        predicates:
        - Path=/user-api/**
      - id: nozama-userservice
        uri: https://nozama-user-service:8081
        predicates:
        - Path=/user-sw/**
      - id: nozama-userauthservice
        uri: https://nozama-user-auth-service:8089
        predicates:
        - Path=/auth/**  
      - id: nozama-userauthservice
        uri: https://nozama-user-auth-service:8089
        predicates:
        - Path=/auth-health/**  
      - id: nozama-userauthservice
        uri: https://nozama-user-auth-service:8089
        predicates:
        - Path=/userauth-sw/**  
      - id: nozama-userauthservice
        uri: https://nozama-user-auth-service:8089
        predicates:
        - Path=/userauth-api/**
      - id: nozama-cartservice
        uri: http://${HOST_NAME:localhost}:${eureka_port:8088}
        predicates:
        - Path=/cart/** 
      - id: nozama-cartservice
        uri: http://${HOST_NAME:localhost}:${eureka_port:8088}
        predicates:
        - Path=/cart-api/** 
      - id: nozama-cartservice
        uri: http://${HOST_NAME:localhost}:${eureka_port:8088}
        predicates:
        - Path=/cart-sw/** 
      - id: nozama-config-service
        uri: http://${configservice_host:localhost}:${configservice_port:8888}
        predicates:
        - Path=/config/**
      - id: nozama-addressservice
        uri: https://nozama-address-service:8092
        predicates:
        - Path=/address/**
      - id: nozama-addressservice
        uri: https://nozama-address-service:8092
        predicates:
        - Path=/address-sw/**
      - id: nozama-addressservice
        uri: https://nozama-address-service:8092
        predicates:
        - Path=/address-api/**

logging:
  file: 
    path: "../log" 
    name: "${logging.file.path}/${spring.application.name:nozama}_log.log"
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
#      springframework:
#        security: DEBUG
#        type: TRACE

#Prometheus
management:
#  server:
#    port: 8762
  endpoints:
    web:
      exposure:
        include: "*"
 
  endpoint:
    health:
      show-details: always
  metrics:
    tags: 
      application: ${spring.application.name}
      env: dev