server:
  port: 8090 

eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
    prefer-ip-address: true

spring:
  application:
    name: Nozama-API-Gateway
  cloud:
    gateway:
      routes:
      - id: nozama-productservice
        uri: http://localhost:8082
        predicates:
        - Path=/category/**
      - id: nozama-productservice
        uri: http://localhost:8082
        predicates:
        - Path=/product/**
      - id: nozama-orderservice
        uri: http://localhost:8094
        predicates:
        - Path=/order/**
      - id: nozama-userservice
        uri: http://localhost:8081
        predicates:
        - Path=/user/**
      - id: nozama-userauthservice
        uri: http://localhost:8089
        predicates:
        - Path=/auth/**
      - id: nozama-userauthservice
        uri: http://localhost:8089
        predicates:
        - Path=/health/**  
      - id: nozama-cartservice
        uri: http://localhost:8088
        predicates:
        - Path=/cart/** 