server:
  port: 8090 

eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
##This property has to be true, so that it uses the IP address, instead of localhost or 127.0.0.1
    prefer-ip-address: true

spring:
  application:
    name: nozama-api-gateway
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  cloud:
    gateway:
      routes:
      - id: nozama-productservice
        uri: http://nozama-product-service:8082
        predicates:
        - Path=/category/**
      - id: nozama-productservice
        uri: http://nozama-product-service:8082
        predicates:
        - Path=/product/**
      - id: nozama-orderservice
        uri: http://nozama-order-service:8094
        predicates:
        - Path=/order/**
      - id: nozama-userservice
        uri: http://nozama-user-service:8081
        predicates:
        - Path=/user/**
      - id: nozama-userauthservice
        uri: http://nozama-user-auth-service:8089
        predicates:
        - Path=/auth/**  
      - id: nozama-cartservice
        uri: http://${HOST_NAME:localhost}:${eureka_port:8088}
        predicates:
        - Path=/cart/** 
      - id: nozama-config-service
        uri: http://${configservice_host:localhost}:${configservice_port:8888}
        predicates:
        - Path=/config/**
      - id: nozama-addressservice
        uri: http://nozama-address-service:8092
        predicates:
        - Path=/address/**

logging:
  level:
    ROOT: TRACE
