FROM nozama-jdk:base
LABEL maintainer="nozama"
VOLUME /tmp
COPY /target/nozama-user-service.jar /opt/lib/nozama-user-service.jar
EXPOSE 8081
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","/opt/lib/nozama-user-service.jar"]