spring:
  application:
    name: "nozama-orderservice"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://nozama-mysql-container:3306/nozamadb?useSSL=false"
    username: nozama_dba
    password: nozama19

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false

  ## Reference  https://thepracticaldeveloper.com/2018/11/24/spring-boot-kafka-config/:
  kafka:
    consumer:
      group-id: nozama-orderinfoupdater
      auto-offset-reset: earliest

server:
    port: 8084

logging:
  path: "/tmp/nozama/logs"
  file: "${logging.path}/${spring.application.name}_log.log"

  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

  config: "classpath:orderservice-logging-config.xml"

kafka:
  server:
    path: "localhost:9092"
  topic: "order.info.updater"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/