spring:
  application:
    name: "nozama-orderservice"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3310/nozama_order_db?allowPublicKeyRetrieval=true&useSSL=false"
    username: nozama_dba
    password: nozama19

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
    
  jackson:
    serialization:
      fail-on-empty-beans: false

  ## Reference  https://thepracticaldeveloper.com/2018/11/24/spring-boot-kafka-config/:
  kafka:
    consumer:
      group-id: nozama-orderinfoupdater
      auto-offset-reset: earliest

server:
    port: 8084

kafka:
  server:
    path: "localhost:9092"
  topic: "order.info.updater"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/

logging:
  file: 
    path: "../log" 
    name: "${logging.file.path}/${spring.application.name:nozama}_log.log"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
