eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
jwt:
  secret: nozama
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: INFO
      springframework:
        security: DEBUG
        type: TRACE
server:
  error:
    include-stacktrace: never
  port: 8081
spring:
  main:
    allow-circular-references: true
  application:
    name: nozama-userservice
#  config:
#    import:
#    - optional:configserver:${CONFIG_SERVER:http://localhost:8091}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: nozama19
    url: jdbc:mysql://localhost:3310/nozama_user_db?allowPublicKeyRetrieval=true&useSSL=false
    username: nozama_dba
  jackson:
    serialization:
      fail-on-empty-beans: false
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
springdoc:
  swagger-ui:
    path: /sw/swagger-ui.html
ribbon:
  eureka:
    enabled: false