eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
    prefer-ip-address: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
jwt:
  secret: nozama
logging:
  file: 
    path: "../log" 
    name: "${logging.file.path}/${spring.application.name:nozama}_log.log"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: INFO
#      springframework:
#        security: DEBUG
#        type: INFO
server:
  error:
    include-stacktrace: never
  port: 8081
  ssl:
    key-store: file:${NOZAMA_CERT}/localhost/localhost.jks
    key-store-password: password
    key-alias: localhost
    key-store-type: JKS
spring:
  main:
    allow-circular-references: true
  application:
    name: nozama-userservice
#  config:
#    import:
#    - optional:configserver:${CONFIG_SERVER:http://localhost:8091}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: nozama19
    url: "jdbc:mysql://localhost:3310/nozama_user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
    username: nozama_dba
  jackson:
    serialization:
      fail-on-empty-beans: false
  zipkin:
    base-url: http://localhost:9411/
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  config:
    import:
    - "optional:http://localhost:8888/config/"

springdoc:
  api-docs:
    path: /user-api/api-docs
  swagger-ui:
    path: /user-sw/swagger-ui.html
ribbon:
  eureka:
    enabled: false
    
## This is the way we can provide the service proxy url and port to reach the other msa
## The URL is pointing to API Gateway and its port number
addressservice :
  ribbon :
    listOfServers : http://localhost:8092
    
#Prometheus
management:
#  server:
#    port: 8762
  endpoints:
    web:
      exposure:
        include: "*"
 
  endpoint:
    health:
      show-details: always
  metrics:
    tags: 
      application: ${spring.application.name}
      env: local