FROM nozama-jdk:base
LABEL maintainer="nozama"
VOLUME /tmp
COPY /target/nozama-shipment-service.jar /opt/lib/nozama-shipment-service.jar
EXPOSE 8083
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","/opt/lib/nozama-shipment-service.jar"]