server:  port: 8888  spring:  application:    name: nozama-configservice  profiles:    active:    - native, dev    
  cloud:
    config:
      server:
        git:#basedir is the place where the clone copy of config is placed#          basedir: file:///${user.home}/central-config#          uri: file:///E:/workspace/nozama-config/central-config# uri do no include .git at the end of the git link
          uri: https://github.com/balamt/nozama-config          force-pull: true#Any sub folders specify the path, names to search for properties, yml files          search-paths:
          - "central-config"          clone-on-start: true        skip-ssl-validation: true# config server URL will look like http://localhost:8888/config/        prefix: /config        logging:  level:    ROOT: INFO    org.springframework.cloud.config: TRACE    #  security:
#    user:
#      name: configbot#      password: s3cr3t