server:
  port: 8761 
  ssl:
    key-store: /cert/nozama.in.jks
    key-store-password: nozama19
    key-alias: nozama
    key-store-type: PKCS12
    enabled: true

eureka:
  client:
   register-with-eureka: false
   fetch-registry: false
   service-url:
      defaultZone: https://${eureka_host:localhost}:${eureka_port:8761}/eureka/
##This property has to be true, so that it uses the IP address, instead of localhost or 127.0.0.1
  instance:
    prefer-ip-address: true

spring:
  application:
    name: nozama-eureka-server
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

logging:
  file: 
    path: "../log" 
    name: "${logging.file.path}/${spring.application.name:nozama}_log.log"
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
#      springframework:
#        security: DEBUG
#        type: TRACE

#Prometheus
management:
#  server:
#    port: 8762
  endpoints:
    web:
      exposure:
        include: "*"
 
  endpoint:
    health:
      show-details: always
  metrics:
    tags: 
      application: ${spring.application.name}
      env: dev