FROM nozama-jdk:base
LABEL maintainer="nozama"
VOLUME /tmp
COPY /target/nozama-api-gateway.jar /opt/lib/nozama-api-gateway.jar
EXPOSE 8090
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","/opt/lib/nozama-api-gateway.jar"]