eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: https://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
    prefer-ip-address: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
logging:
  file: 
    path: "../log" 
    name: "${logging.file.path}/${spring.application.name:nozama}_log.log"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  port: 8082
  ssl:
    key-store: /cert/nozama.jks
    key-store-password: nozama19
    key-password: nozama19
    key-store-type: JKS
    key-alias: nozama
spring:
  application:
    name: nozama-productservice
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: nozama19
    url: "jdbc:mysql://${NOZAMA_APP_MYSQL_URL:localhost}:${NOZAMA_APP_MYSQL_PORT:3310}/${NOZAMA_APP_MYSQL_DBNAME:nozama_products_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
    username: nozama_dba
  jackson:
    serialization:
      fail-on-empty-beans: false
#  zipkin:
#    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
springdoc:
  api-docs:
    path: /product-api/api-docs
  swagger-ui:
    path: /product-sw/swagger-ui.html

ribbon:
  eureka:
    enabled: false
    
product:
  image:
      location: ${PRODUCT_IMAGE_UPLOAD_PATH:/tmp/product/image}

#Prometheus
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
  endpoint:
    health:
      show-details: always
  metrics:
    tags: 
      application: ${spring.application.name}
      env: dev