FROM nozama-jdk:base
LABEL maintainer="nozama"
VOLUME /tmp
COPY /target/nozama-product-service.jar /opt/lib/nozama-product-service.jar
EXPOSE 8082
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","/opt/lib/nozama-product-service.jar"]