spring:
  application:
    name: "nozama-addressservice"

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:nozama_address_db;DB_CLOSE_DELAY=-1"
#    username: sa
#    password: 

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
        
  zipkin:
    base-url: http://${zipkin.host:localhost}:${9411:9411}/
    
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
    port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/

logging:
  file: 
    path: "../log" 
    name: "${logging.file.path}/${spring.application.name:nozama}_log.log"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: INFO
