FROM nozama-jdk:base
LABEL maintainer="nozama"
VOLUME /tmp
RUN rm -Rf /tmp/*
#RUN apk add --no-cache --upgrade bash
COPY ./zipkin/zipkin-server-2.23.9-exec.jar /opt/lib/zipkin-server-2.23.9-exec.jar
COPY /cert /opt/lib
EXPOSE 9411
ENTRYPOINT ["/usr/bin/java"]
#java -jar zipkin.jar --armeria.ssl.key-store=zipkin.p12 --armeria.ssl.key-store-type=PKCS12 --armeria.ssl.key-store-password=123123 --armeria.ssl.key-alias=koushik9951  --armeria.ssl.enabled=true --armeria.ports[0].port=9411 --armeria.ports[0].protocols[0]=https
#ZIP need JKS format for loading the keystore
CMD ["-jar","/opt/lib/zipkin-server-2.23.9-exec.jar","--armeria.ssl.key-store=/opt/lib/nozama.in.jks","--armeria.ssl.key-store-type=JKS","--armeria.ssl.key-store-password=nozama19", "--armeria.ssl.key-alias=nozama","--armeria.ssl.enabled=true","--armeria.ports[0].port=9411","--armeria.ports[0].protocols[0]=https"]
