FROM ubuntu/prometheus:latest
LABEL maintainer="nozama"
VOLUME /tmp
COPY ./prometheus.yml /etc/prometheus/prometheus.yml
EXPOSE 8763
ENTRYPOINT ["/bin/prometheus"]
CMD ["--config.file=/etc/prometheus/prometheus.yml"]