version: '3'

services:
  nozama-mysql:
    image: nozama_mysql:base
    #Instead of container name user hostname, if container name is used will cause mysql access issue to services
    container_name: nozama-mysql
    hostname: mysql.nozama.in
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nozamadb
      - MYSQL_USER=nozama_dba
      - MYSQL_PASSWORD=nozama19
      - MYSQL_ROOT_HOST=%
    networks:
      - nozama_net
    ports:
      - 3308:3306
    restart: always
    
  nozama-prometheus:
    image: nozama-prometheus:base
    #Instead of container name user hostname, if container name is used will cause mysql access issue to services
    container_name: nozama-prometheus
    hostname: prometheus.nozama.in
    environment:
      - eureka_host=sd.nozama.in
      - eureka_port=8761
    networks:
      - nozama_net
    ports:
      - 8763:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
      - ./cert:/cert
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    restart: always
    
  nozama-grafana-container:
    image: nozama-grafana:base
    #Instead of container name user hostname, if container name is used will cause mysql access issue to services
    container_name: nozama-grafana
    hostname: grafana.nozama.in
    environment:
      - eureka_host=sd.nozama.in
      - eureka_port=8761
    networks:
      - nozama_net
    ports:
      - 8764:3000
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prometheus-data:/prometheus
#    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    restart: always
    
  nozama-ui-container:
    image: nozama-ui:1
    container_name: nozama-ui
    hostname: nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
    build:
      context: ../nozama-ui/
      dockerfile: Nozama_UI_DockerFile
    ports:
      - 8080:80
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

  nozama-eureka-server-container:
    depends_on:
      - nozama-mysql
    image: nozama-eureka-server:1
    container_name: nozama-eureka-server
    hostname: sd.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
#      - eureka_host=sd.nozama.in
#      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
    build:
      context: ./Nozama_EurekaServer/
      dockerfile: DockerFile
    ports:
      - 8761:8761
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

  nozama-api-gateway-container:
    depends_on:
      - nozama-mysql
    image: nozama-api-gateway:1
    container_name: nozama-api-gateway
    hostname: apigw.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
      - user_service_host=user.nozama.in
      - configservice_host=config.nozama.in
      - configservice_port=8888
    build:
      context: ./Nozama_ApiGateway/
      dockerfile: DockerFile
    ports:
      - 8090:8090
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always
    
  nozama-config-service-container:
#    depends_on:
#      - nozama-mysql
    image: nozama-config-service:1
    container_name: nozama-config-service
    hostname: config.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
      - nozama_api_host=apigw.nozama.in
      - nozama_api_port=8090
      #Need to remove the below two properties and see if it works.
#      - nozama.sql.host.address=nozama-mysql
#      - nozama.sql.host.port=3306
    build:
      context: ./Nozama_ConfigService/
      dockerfile: DockerFile
    ports:
      - 8888:8888
#    links:
#      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

  nozama-user-service-container:
    depends_on:
      - nozama-mysql
    image: nozama-user-service:1
    container_name: nozama-user-service
    hostname: user.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_user_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
#      - zipkin.host=zipkin.nozama.in
#      - nozama_api_host=apigw.nozama.in
#      - nozama_api_port=8090
      #Need to remove the below two properties and see if it works.
#      - nozama.sql.host.address=mysql.nozama.in
#      - nozama.sql.host.port=3306
    build:
      context: ./Nozama_UserService/
      dockerfile: DockerFile
    ports:
      - 8081:8081
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
#If we need to point local folder to docker container, we specify as below - <host_foler_path>:<target_container_volume_path>
      - ./cert:/cert
    restart: always
    
  nozama-user-auth-service-container:
    depends_on:
      - nozama-mysql
    image: nozama-user-auth-service:1
    container_name: nozama-user-auth-service
    hostname: auth.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_user_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
      - nozama_api_host=apigw.nozama.in
      - nozama_api_port=8090
      #Need to remove the below two properties and see if it works.
      - nozama.sql.host.address=mysql.nozama.in
      - nozama.sql.host.port=3306
    build:
      context: ./Nozama_UserAuthService/
      dockerfile: DockerFile
    ports:
      - 8089:8089
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

  nozama-product-service-container:
    depends_on:
      - nozama-mysql
    image: nozama-product-service:1
    container_name: nozama-product-service
    hostname: product.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_products_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
      - nozama.sql.host.address=mysql.nozama.in
      - nozama.sql.host.port=3306
      - PRODUCT_IMAGE_UPLOAD_PATH=/product/image/
    build:
      context: ./Nozama_ProductService/
      dockerfile: DockerFile
    ports:
      - 8082:8082
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
      - /product
    restart: always

  nozama-order-service-container:
    depends_on:
      - nozama-mysql
    image: nozama-order-service:1
    container_name: nozama-order-service
    hostname: order.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_order_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
#      - nozama.sql.host.address=mysql.nozama.in
#      - nozama.sql.host.port=3306
    build:
      context: ./Nozama_OrderService/
      dockerfile: DockerFile
    ports:
      - 8084:8084
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

  nozama-shipment-service-container:
    depends_on:
      - nozama-mysql
    image: nozama-shipment-service:1
    container_name: shipment.nozama.in
    hostname: nozama-shipment-service
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_shipment_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
#      - nozama.sql.host.address=mysql.nozama.in
#      - nozama.sql.host.port=3306
    build:
      context: ./Nozama_ShipmentService/
      dockerfile: DockerFile
    ports:
      - 8083:8083
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

  nozama-delivery-batch-container:
    depends_on:
      - nozama-mysql
    image: nozama-delivery-batch:1
    container_name: nozama-delivery-batch-service
    hostname: delivery.batch.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_delivery_schedule_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
#      - nozama.sql.host.address=mysql.nozama.in
#      - nozama.sql.host.port=3306
    build:
      context: ../nozama-batch/Nozama_DeliveryScheduler/
      dockerfile: DockerFile
    ports:
      - 8085:8085
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

  nozama-zipkin-container:
    image: nozama-zipkin:1
    container_name: nozama-zipkin
    hostname: zipkin.nozama.in
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_delivery_schedule_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
#      - nozama.sql.host.address=mysql.nozama.in
#      - nozama.sql.host.port=3306
    build:
      context: ./zipkin/
      dockerfile: DockerFile
    ports:
      - 9411:9411
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always
    
  nozama-address-service-container:
    depends_on:
      - nozama-mysql
    image: nozama-address-service:1
    container_name: address.nozama.in
    hostname: nozama-address-service
    environment:
      - NOZAMA_SERVICE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.nozama.in:3306/nozama_user_db?allowPublicKeyRetrieval=true&useSSL=false
      - eureka_host=sd.nozama.in
      - eureka_port=8761
      - zipkin.host=zipkin.nozama.in
      - nozama_api_host=apigw.nozama.in
      - nozama_api_port=8090
      #Need to remove the below two properties and see if it works.
#      - nozama.sql.host.address=mysql.nozama.in
#      - nozama.sql.host.port=3306
    build:
      context: ./Nozama_AddressService/
      dockerfile: DockerFile
    ports:
      - 8092:8092
    links:
      - nozama-mysql:nozama_mysql
    networks:
      - nozama_net
    volumes:
      - /tmp
      - ./cert:/cert
    restart: always

networks:
  nozama_net:
    driver: bridge
    
volumes:
  prometheus-data:
  nozama-share: 
  