FROM nozama-jdk:base
LABEL maintainer="nozama"
VOLUME /tmp
COPY /target/nozama-eureka-server-0.0.1-SNAPSHOT.jar /opt/lib/nozama-eureka-server-0.0.1-SNAPSHOT.jar
EXPOSE 8761
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","/opt/lib/nozama-eureka-server-0.0.1-SNAPSHOT.jar"]