FROM nozama-jdk:base
LABEL maintainer="nozama"
VOLUME /tmp
COPY /target/nozama-eureka-server.jar /opt/lib/nozama-eureka-server.jar
EXPOSE 8761
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","/opt/lib/nozama-eureka-server.jar"]